Feature/models
SvyatoslavFedynyak/Galagram pull request #25
Opened 2018-12-02 11:41 UTC by vasil98

2018-12-02 19:17 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Comment.cs
> +        public Comment(int id, User author, System.Collections.Generic.ICollection<Like> likes, string text, System.DateTime date)
Don't need here constructors with params. Only parameterless

2018-12-02 19:24 UTC, SvyatoslavFedynyak requested changes

2018-12-02 19:24 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Comment.cs
> +        /// Constructor with parameters
Don't need here constructors with params. Only parameterless. In all entities, so it should be 6 changes

2018-12-02 19:24 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Message.cs
> +        private int id;
Not important. Fields are private by default.

2018-12-02 19:27 UTC, iamprovidence commented on Galagram/Models/Entities/Message.cs
> +        private int id;
however it not a problem. and code become easier to read

2018-12-02 19:34 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Message.cs
> +        private int id;
> 
> 
> however it not a problem. and code become easier to read
>
I don't think its easier, and if you'll spend 5 sec for every "private" you may lose a minute for every 12 fields)

2018-12-02 19:40 UTC, iamprovidence commented on Galagram/Models/Entities/Message.cs
> +        private int id;
still think it is not a problem. you know, sometimes missing access modifier can lead to more problems than missing minute, for example missing an hour to rework project carcass. but as you think

2018-12-02 19:42 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Message.cs
> +        private int id;
I don't want him to rework it. Only for future

2018-12-02 19:47 UTC, iamprovidence commented on Galagram/Models/Entities/Message.cs
> +        private int id;
Even for future, still think it is not a problem. But as you wish

2018-12-02 20:12 UTC, vasil98 commented on Galagram/Models/Entities/Comment.cs
> +        /// Constructor with parameters
then constructor with parameters at all to remove ?

2018-12-02 21:18 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Comment.cs
> +        /// Constructor with parameters
Yes. Need only default

2018-12-03 08:37 UTC, SvyatoslavFedynyak commented on Galagram/Models/Entities/Comment.cs
> +        /// Constructor with parameters
Yes. We need just default.

2018-12-03 19:23 UTC, SvyatoslavFedynyak approved these changes

2018-12-03 19:23 UTC, merged